version: '3.8'

services:
  api:
    build: .
    command: api
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./data:/app/data:rw
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${API_PORT}/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  worker:
    build: .
    command: worker
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep 'worker' | grep -v grep || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
