version: '3.8'

services:
  api:
    build: .
    command: api
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - data_volume:/app/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${API_PORT}/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  volumes:
    data_volume:
      name: s3_document_processor_data

  worker:
    build: .
    command: worker
    volumes:
      - data_volume:/app/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${WORKER_PORT}/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
